### ISSUE TITLE
Chunking structure of the pyramids

### ISSUE THREAD

**Issue by felixcremer** [JuliaDataCubes/PyramidScheme.jl#7]
Currently, I think, we are going to impose the chunking structure of the input dataset also into the pyramids.

Do we want to set a default chunk structure, so that we optimize for the map access that we are going to use the data for?
What chunk structure would we like to have on the data?

For the highest pyramid level we could use one chunk for the whole array, but for the lower levels this could be the same as the underlying tile size that we would like to aim for in the highest pyramid level.

**Comment by meggart** [comment]
We do not infer the chunking from the input but hard-code it to 1024 x 1024, see this line here: https://github.com/JuliaDataCubes/PyramidScheme.jl/blob/df90034d527fa66a97947a0d0790b106ea391bc1/src/PyramidScheme.jl#L137

Of course you are free to choose whatever chunk size you like here.
